services:
  api:
    build: .
    restart: unless-stopped
    env_file: ./.env
    environment:
      - NODE_ENV: production
    ports:
      - 8022:8022
    depends_on:
      - db

  db:
    image: mongodb/mongodb-community-server
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - db:/data/db



volumes:
  db: