services:
  api:
    build: .
    restart: unless-stopped
    env_file: ./.env
    environment:
      - NODE_ENV=production
    ports:
      - 8022:8022
    depends_on:
      - db

  db:
    image: mongodb/mongodb-community-server
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DBUSER}
      - MONGO_INITDB_ROOT_PASSWORD=${DBPASS}
    volumes:
      - db:/data/db



volumes:
  db: